### ISSUE TITLE
关于登录的相关安全处理

### ISSUE THREAD

**Issue by brucemeteor** [TerryZ/vuepress-login#1]
登录只是做一个弹窗，其实没有意义，因为弹窗可以被界面隐藏掉。
所以这个只是拦截了一部分不懂的开发的小白，
在通过删除HTML元素或者隐藏元素后，就可以肆无忌惮的访问界面了，
所以这个安全处理其实还设有完全达标。

**Comment by TerryZ** [comment]
抛砖引玉的演示而已，更高级别的安全限制当然要根据自己的实际情况去修改，还指望这种项目开箱即用么？
