### ISSUE TITLE
是否能够实现用户登录后才加载文档内容？

### ISSUE THREAD

**Issue by helixzz** [TerryZ/vuepress-login#8]
虽然在用户未登录的情况下会显示模态的登录窗口，但：

1. 登录窗口背后的文档依然可以滚动浏览；
2. 通过 F12 等调试手段可以轻而易举地删掉登录窗口。

这样就起不到保护内容的作用啦。

**Comment by TerryZ** [comment]
这只是个功能 demo，演示了怎么为站点增加登录的功能，有更多需求自然要自行实现
